<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE ENTREGA [
  <!ELEMENT ENTREGA (LOTE*)>
  <!ELEMENT LOTE (PALET*)>
  <!ELEMENT PALET (num_CAJAS, PESO_NETO, CONTENIDO, FORMA_MANIPULACIÓN)>
  <!ELEMENT num_CAJAS (#PCDATA)>
  <!ELEMENT PESO_NETO (#PCDATA)>
  <!ELEMENT CONTENIDO (NOMBRE_COMPONENTE, PROCEDENCIA, num_SERIE, PESO, UNIDAD_PESO)>
  <!ELEMENT NOMBRE_COMPONENTE (#PCDATA)>
  <!ELEMENT PROCEDENCIA (#PCDATA)>
  <!ELEMENT num_SERIE (#PCDATA)>
  <!ELEMENT PESO (#PCDATA)>
  <!ELEMENT UNIDAD_PESO (#PCDATA)>
  <!ELEMENT FORMA_MANIPULACIÓN (#PCDATA)>
]>
<ENTREGA>
    <LOTE>
        <PALET>
            <num_CAJAS>23</num_CAJAS>
            <PESO_NETO>345.50</PESO_NETO>
            <CONTENIDO>
                <NOMBRE_COMPONENTE></NOMBRE_COMPONENTE>
                <PROCEDENCIA></PROCEDENCIA>
                <num_SERIE></num_SERIE>
                <PESO></PESO>
                <UNIDAD_PESO></UNIDAD_PESO>
            </CONTENIDO>
            <FORMA_MANIPULACIÓN></FORMA_MANIPULACIÓN>
        </PALET>
    </LOTE>
</ENTREGA>
